// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  let badge = "https://img.shields.io/badge/License-Boost%201.0-lightblue.svg";

  if (license === "") return "";

  if (license === "MIT") {
    return (badge = "https://img.shields.io/badge/License-MIT-yellow.svg");
  } else if (license === "Apache") {
    return (badge =
      "https://img.shields.io/badge/License-Apache%202.0-blue.svg");
  } else if (license === "Mozilla") {
    return (badge =
      "https://img.shields.io/badge/License-MPL_2.0-brightgreen.svg");
  } else if (license === "npm") {
    return (badge = "https://img.shields.io/badge/npm-npm-brightgreen");
  } else if (license === "node") {
    return (badge = "https://img.shields.io/node/v/gh-badges.svg");
  } else if (license === "inquirer") {
    return (badge = "https://img.shields.io/badge/inquirer-8.2.4-blue");
  } else {
    return badge;
  }
}

//["MIT", "Apache", "Mozilla", "npm", "inquirer", "node"],
// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  let link = "https://www.boost.org/LICENSE_1_0.txt";
  if (license === "MIT") {
    return (link = "https://opensource.org/licenses/MIT");
  } else if (license === "Apache") {
    return (link = "https://opensource.org/licenses/Apache-2.0");
  } else if (license === "Mozilla") {
    return (link = "https://opensource.org/license/mit/");
  } else if (license === "npm") {
    return (link = "https://docs.npmjs.com/policies/npm-license");
  } else if (license === "inquirer") {
    return (link = "https://www.npmjs.com/package/inquirer");
  } else if (license === "node") {
    return (link = "https://nodejs.org/en/download");
  } else {
    return link;
  }
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  if (license === "") return "";
  else {
    var link = renderLicenseLink(license);
    var badge = renderLicenseBadge(license);
    var licenseBadge = `[![License:](${badge})](${link})`;
    return licenseBadge;
  }
}

function generateMarkdown(data) {
  console.log("Ansewers: ", data);
  const licenseBadge = renderLicenseSection(data.license);
  console.log("License: ", licenseBadge);
  return `
  <h1 align="center">${data.projectTitle}</h1>
  <br/>

  ${licenseBadge} <br/>

    ## Description
    ${data.projDesc}

    ## Table of Contents
    - [Description](#description)
    - [Installation](#installation)
    - [Usage](#usage)
    - [License](#license)
    - [Contributing](#contributing)
    - [Tests](#tests)
    - [Questions](#questions)

    ## Installation
    ${data.installationSteps}

    ## Usage
    ${data.proUsage}

    ## License
    ![badge](https://img.shields.io/badge/license-${data.license}-brightgreen)
    <br />
    This application is covered by the ${data.license} license.   

    ## Contributing
    ${data.proContribution}

    ## Tests
    ${data.protests}
  

    ## Questions
    ${data.questions}<br />
    <br />
    * GitHub UserName: [${data.username}]
    * GitHub Profile: [${data.profileURL}]<br />
   
    <br />
    Email: ${data.emailAddress}
    <br /><br />
   
    This README was generated by ${data.username}: [README-generator](${data.repourl})


`;
}

module.exports = generateMarkdown;
